name: Diesel CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
            java-version: 13
      - name : checkout
        uses: actions/checkout@v2
      - name: Build & Deploy
        run: mvn -B clean install && HEROKU_API_KEY=${{ secrets.HEROKU_AUTH_TOKEN }} mvn clean heroku:deploy
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: Evulution.postman_collection.json
          environment: Evulution_prod.postman_environment.json
          reporters: cli
